### PR TITLE
Add Vue Test Utils

### PR DESCRIPTION
**Pull request by liam-mulhall**
This commit adds Vue Test Utils, which is "a set of utility
functions aimed to simplify testing Vue.js components". It
allows us to unit test Vue components.

I was originally trying to set up the Jest testing framework for general testing purposes, but I was running into lots of issues. My plan is to further configure Jest for general testing purposes now that I've got Vue Test Utils working.

To test this PR:

1. `npm run test:unit` should output something like the following
```
> newnumberscope@0.2.0 test:unit
> vue-cli-service test:unit

 PASS  tests/unit/SeqGetter.spec.ts
  ✓ displays dummy title (21ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.828s
Ran all test suites.
```
2. `npm run serve` should compile successfully
3. you should be able to interact with Numberscope in your browser as usual

### CODE REVIEW

**Comment by gwhitney** [comment]
A few comments/questions:
1) How does this interact with PR #38? At the very least, if they were both merged, we would have `npm run test` running whatever TypeScript tests we set up in jest and `npm run test:unit` running Vue tests. Those two commands don't seem parallel or mnemonic for the two alternatives. Should this one be `npm run test:vue` and the other be modified to `npm runt test:ts` or something like that? Please just make sure you are heading to a rational collection of test directives, thanks.
2) I see that you've (whitespace-)reformatted the list of parameters in .eslintrc.js, as well as added the new "overrides" parameter. Some projects prefer to minimize the lines touched in functional PRs, and leave such reformatting to format-only PRs. I don't myself much care especially for a fairly lean PR like this one, but if you would prefer that approach that separates functional PRs from format PRs, you might want to leave the spacing alone in this PR.
3) I see the one test for SeqGetter just checks that it displays the title. But somehow the "essence" of a SeqGetter seems more that it emits a `load-seq` signal when it is clicked. Is that a sort of thing that can be tested in this framework? If so, could you add a test for that -- mostly because it would make your one example test a better guide for folks who will have to write tests for other Components (which will presumably become mandatory for future PRs).
4) Your Jest PR #38 in progress added a documentation file about testing. Even though we haven't resolved #71, should this PR have something like that for Vue testing, in some reasonable place that can be rearranged depending on how #71 turns out? If so, that file should likely also mention that providing a working, reasonably complete unit test for all affected Vue components is mandatory for all future PRs that touch a Vue component.
5) What about testing views? Is that doable with this framework, or does it only test components? Some mention of that point would be nice somewhere in this PR, for example in the doc file if you add one, or in some other reasonable place if not.
I am going to unassign myself because really once there are responses to these questions, anyone could move the PR on from there.

**Comment by liam-mulhall** [comment]
1. This morning, I initially set out to work on https://github.com/numberscope/frontscope/pull/38, but as I mentioned, I was running into too many issues. The plan is to essentially scrap the work done for that PR and instead build off of this PR. I can delete https://github.com/numberscope/frontscope/pull/38 once I'm sure there isn't anything useful in it. As you suggest, I was planning on doing something like `npm test:vue` and `npm test:ts` for the two different types of testing. I think the exact names for the test directives can be decided upon later. I'm just trying to get things working at this point.
2. That formatting wasn't added by me; it was done automatically when installing Vue Test Utils. I can remove it.
3. I can add a more comprehensive test for `SeqGetter`, but that wasn't really the point of this PR. The point of this PR is to add Vue Test Utils. I only added the test so that we'd have a means to ensure Vue Test Utils is working properly. I just wanted to add a "Hello, World!" for Vue Test Utils. Would you like me to add a more comprehensive test for `SeqGetter` in this PR, @gwhitney?
4. I'd like to add a file `doc/tests.md` that goes over how to add a test for Vue components and how to add a test for TS once we're able to do both of those things and once things like the names for the test directives have been decided upon. In other words, once things are more settled, I will add that doc.
5. Yes. See https://github.com/liam-mulhall/frontscope/commit/8bda358c6ffa0edf1816a4a53a8549087238488f. I can add this to the doc.

**Comment by gwhitney** [comment]
State of the items below. As far as I am concerned, all that remains -- except I feel a little stronger than that about the new (6) -- are optional suggestions. Just let me know whether or not you're going to take any action with respect to them, and then I'll wrap up this PR and merge it.
1) Thanks for explaining that #38 is to be superseded. As to the name of the directive to run the test, I totally agree that we can't expect - and shouldn't attempt to force - the specifics of any PR to be the permanent state of affairs. That said, I think it's good practice all else being equal to have as many aspects of a PR as practical be your current best guess of the final state of things. So if the name "test:unit" seems unlikely to be the final directive, I'd suggest you change it in this PR to your best current guess of what that final directive should be.

2) Fully resolved.

3) I understand the point of this PR wasn't to test SeqGetter in particular, but of course adding a testing framework has to include at least a test or two. The addition of the Home test is nice, and that test is pretty much comprehensive; not sure what else you would test about the Home view. So it seems to me that it would make a better introduction, and example for future PRs to follow, to start with each of your initial tests being essentially comprehensive for the components you chose as "guinea pigs." That will have the side effect of demonstrating a slightly larger range of testing techniques, as well. And it doesn't look like much more work, since as far as I can see, there's really only one other thing to test about a SeqGetter. And if it isn't done at this point, when the SeqGetter test is being introduced, when will that test be made comprehensive? Only when somebody touches SeqGetter.vue, and then only if the PR writer or reviewer notice/remember at that juncture that the SeqGetter test isn't comprehensive. So I'd suggest that this is the time to make a comprehensive SeqGetter test; but as I said it's just a suggestion and once you respond I will follow through with this PR either way.

4) You might want to file an issue immediately about the need for some doc on the testing framework, if you're not including even a stub of that in this PR.

5) Fully resolved.

6) Why did you delete the final newline of tsconfig.json? It doesn't seem relevant to the content changes you made to the file, and as far as I am concerned every line of a source file should end in newline, and in any case we definitely need to not get into a cycle of going back and forth on final newlines -- this is an item that should be standardized and be in the eventual document produced by #69. I will add a comment there, and for now I'd recommend you leave alone the final newline that's already in this file.

**Comment by liam-mulhall** [comment]
1. My best guess right now is `npm run test:vue`. I will rename the script. (The command `vue-cli-service test:unit` can't be easily renamed, so I'll leave that as is.) Done in https://github.com/numberscope/frontscope/pull/72/commits/98a41622df6ece4a1ae8efd2925061bcfe0c32f0.
2. Resolved.
3. Added additional test for `SeqGetter` that ensures a `load-seq` is emitted when clicked in https://github.com/numberscope/frontscope/pull/72/commits/4bf71ae0dc60387f72386e157068be2221933613.
4. Done in https://github.com/numberscope/frontscope/issues/73.
5. Resolved.
6. I've never faced an issue where not having a newline at the end of a file has presented issues in the web dev projects I've worked on, but I'm happy to follow best practices here. Newline added in https://github.com/numberscope/frontscope/pull/72/commits/704d1a35d8219a83ae66d05987704d4b659733cf.

**Comment by gwhitney** [comment]
All looks good. I will merge, and consider supplying tests for Vue components and views that are touched to be mandatory going forward (that should of course go in our submission documentation).

On (6), I fear you mistook the source of the strength of my recommendation. I am not terribly concerned about final newlines; note I did not even previously comment on the new source file you added that lacks one. I am just concerned about going back and forth on their presence. (My editor automatically adds them, yours clearly doesn't, and we don't want git history muddled up with lots of changes back and forth on this.) Hence, the thing I am concerned with is that at some point fairly soon, we pick one convention or the other, do a one-time update to uniformize, and then stick with that convention. In the meantime, we shouldn't unnecessarily change any particular source file in this respect.

**Comment by liam-mulhall** [comment]
Hey, no worries. I like to pick a convention and stick with it. I'm sure I can get at least an ESLint rule to enforce newlines at the end of files. Maybe Prettier will have an option. I can also configure my various editors to do it as well. Anyway, we have lots of tools at our disposal.

**Comment by liam-mulhall** [comment]
I think making tests for a touched file mandatory is a good idea.

**Pull request merged**
