### PR TITLE
doc/ui: Skin documentation site to match Numberscope

### PR DESCRIPTION
**Pull request by gwhitney**
Now the NavBar appears essentially unchanged when switching between
  doc pages (like About or Documentation) and app pages (like the home
  page and the 'scope itself).

  Resolves https://github.com/numberscope/frontscope/issues/141.

### CODE REVIEW

**Comment by gwhitney** [comment]
Don't forget to npm install when pulling this PR.

**Comment by liam-mulhall** [comment]
Looks great on desktop, but when I tried to check how it would look on mobile, I noticed this:

issue

I think we should try to avoid making the website look bad on mobile. It's true that users almost certainly won't want to use the app on mobile, but someone might discover it on mobile (e.g. via Twitter), and we need to make a good first impression.

**Comment by liam-mulhall** [comment]
@gwhitney, would it be difficult to fix this? To check how a site will look on mobile on Firefox, right click the page > Inspect > click the mobile devices icon.

firefox

**Comment by gwhitney** [comment]
Happy to fix. Not sure exactly when, although perhaps I can squeeze it in before I leave, as it should be quick. But what would really help is if you can provide specific feedback on the changes to the portrait view of the page you would like. Is there anything beyond the color mismatch at the top? I guess we should not repeat the word "Numberscope"; should there be anything in place of the second occurrence of Numberscope?

Having a hamburger menu both at the top right and near-top left is not ideal, but I am really not sure what to do about that: one is from the overall-site menu, and the other is from documentation navigation. So my feeling is that we should not sweat this too much as getting the mobile docsite just perfect is probably not worth our effort -- it just shouldn't look too amateurish/broken. That said, if you have any changes for the  portrait arrangement of the docsite navigation controls, especially ones that can be accomplished just with CSS, I am happy to take care of them. But at the moment very specific action items is really helpful given  the pressures on my time.

**Comment by liam-mulhall** [comment]
Perhaps add a media query for mobile that increases the height of the Numberscope navbar so that the docsite navbar is covered up?

**Comment by liam-mulhall** [comment]
I can try to fiddle with it if you're too pressed for time, @gwhitney.

**Comment by liam-mulhall** [comment]
Oh, wait I think covering up the docsite navbar would make it so that you can't navigate using the links in the sidebar on mobile. Hmm... I'll try to think of another solution.

**Comment by gwhitney** [comment]
If you want to fiddle, feel free, or just provide specific thoughts on what to do besides the color matching. I can likely get to it sometime tomorrow or Thursday. But I am  very reluctant to obscure all controls for navigating the documentation; I think there needs to be access to the doc outline.  Perhaps I can just color-match and remove _all_ of the doc nav bar **except** for the doc's hamburger menu, revealing more space for the doc content underneath most of the site navbar, which we would leave alone to match the tool itself?  How does that sound?

**Comment by liam-mulhall** [comment]
> How does that sound?

That sounds good.

**Comment by gwhitney** [comment]
OK, will try to get to this in the next day or two.

**Comment by gwhitney** [comment]
OK I found a few minutes to monkey around with this. How's the latest commit look?

**Comment by liam-mulhall** [comment]
The latest commit looks much better! Thanks @gwhitney. I'm going to merge. (I meant to comment this before merging.)

**Pull request merged**
