### PR TITLE
doc: Restore broken and missing links 

### PR DESCRIPTION
**Pull request by gwhitney**
By submitting this PR, I am indicating to the Numberscope maintainers that I have read and understood the [contributing guidelines](https://numberscope.colorado.edu/doc/CONTRIBUTING/) and that this PR follows those guidelines to the best of my knowledge. I have also read the [pull request checklist](https://numberscope.colorado.edu/doc/doc/pull-request-checklist/) and followed the instructions therein.

<hr/>
  Over a number of commits, numerous missing and broken links in the
  MkDocs documentation for Numberscope had accumulated. This PR restores
  all MkDocs links to working order, including re-creating a section
  on submitting a pull request that had somehow been lost altogether in
  a previous documentation refactor.

  When this commit is checked out, `npm run doc:serve` should not issue
  any warnings or info messages mentioning files that contain a link
  that do not correspond to any actual files or anchors in the system.

### CODE REVIEW

**Comment by katestange** [comment]
There's this file, should we integrate it with what you added.... ?https://github.com/numberscope/frontscope/blob/d0ea3a4c97e930dd167765b49a5d35e698f00a2a/doc/pull-request-checklist.md?plain=1#L2

**Comment by Vectornaut** [comment]
The fixes that have been made here look good, but I'm having trouble verifying that all the bad links have been fixed.

When I run `doc:serve` on the main branch, I only see one info or warning message about broken links: the one about the bad image link in the Entries user guide. The other broken links are still present, but when I search the `doc:serve` output for parts of the bad URLs (for example, "p5"), I don't find anything.

Is there some flag I need to set in order to get more messages?

**Comment by gwhitney** [comment]
> There's this file, should we integrate it with what you added.... ?
> 
> https://github.com/numberscope/frontscope/blob/d0ea3a4c97e930dd167765b49a5d35e698f00a2a/doc/pull-request-checklist.md?plain=1#L2

Oh, good point. I will push a commit.

**Comment by gwhitney** [comment]
> > There's this file, should we integrate it with what you added.... ?
> > https://github.com/numberscope/frontscope/blob/d0ea3a4c97e930dd167765b49a5d35e698f00a2a/doc/pull-request-checklist.md?plain=1#L2
> 
> Oh, good point. I will push a commit.

OK, I have now linked to the PR checklist. Also gave me the opportunity to fix the outline of the working with git page, and fix a couple typos. How's that look now?

**Comment by katestange** [comment]
> OK, I have now linked to the PR checklist. Also gave me the opportunity to fix the outline of the working with git page, and fix a couple typos. How's that look now?

Great!

**Comment by gwhitney** [comment]
All right well nobody hold back on merging ;-)

**Review by katestange — APPROVED** [review]

**Pull request merged**
