### PR TITLE
doc: Small fixes to running-from-source

### PR DESCRIPTION
**Pull request by gwhitney**
By submitting this PR, I am indicating to the Numberscope maintainers that I have read and understood the [contributing guidelines](https://numberscope.colorado.edu/doc/CONTRIBUTING/) and that this PR follows those guidelines to the best of my knowledge. I have also read the [pull request checklist](https://numberscope.colorado.edu/doc/doc/pull-request-checklist/) and followed the instructions therein.

<hr/>

Resolves https://github.com/numberscope/frontscope/issues/155.

### CODE REVIEW

**Comment by gwhitney** [comment]
Note the link to the husky file is obliged to have a different form in the repo and on the docsite, since MkDocs does not serve files in directories whose names begin with `.` -- therefore, this PR adds a facility so that Markdown files in our docs can provide alternatives to be visible in the repository and in the docsite via a block of the form:
```
<!-- repository -->
Note repository markdown goes here. It will be visible in the
github markdown display because it is uncommented. Immediately
after this block must be a docsite comment like:
<!-- docsite: This will be extracted into docsite, but is invisible in repo because commented. It must be on one line. -->
```

**Comment by liammulh** [comment]
When I `npm run build`:

```
WARNING  -  Documentation file 'doc/running-from-source.md' contains a link
            to 'husky/pre-commit.txt' which is not found in the
            documentation files.
```

Do we want to ignore this? If so, we need to add a line to the PR checklist saying it's OK to ignore. If not, it needs to be fixed.

The information contained in https://github.com/numberscope/frontscope/pull/202#issuecomment-1316032494 would be useful to have in the docs themselves. It seems a bit weird to have docs about docs, but I don't expect people who write docs to either find this PR comment or read `mkdocs.yml` and grok what is going on in there.

**Comment by gwhitney** [comment]
OK, I will use a different strategy I came up with afterwards for providing this information, that should avoid both this warning and the need for tricky html comments in the docs. Will add a commit for this soon.

**Comment by gwhitney** [comment]
Alright, that should be better. Now there is just a

`<!-- CUT HERE -->`

directive. Everything below that will not appear in the doc site. I've used this and ordinary content extraction to create a little appendix on the doc site that lists the Husky pre-commit actions, whereas on github you just see the extraction marker, but there is an additional direct link to the Husky actions for convenience when viewing it that way. Let me know if this all strikes you as OK. I think it's simpler, and it generates no warnings.

**Comment by liammulh** [comment]
This does seem simpler. Aside from it looking kinda weird when you view the raw markdown, I'm OK with this.

**Comment by liammulh** [comment]
Looks good when I test it locally. I'm OK with merging, but maybe @katestange will have ideas. I'll wait for meeting.

**Comment by gwhitney** [comment]
I agree it's a bit weird. But the raw markdown is maintained by authors; the key for usability is that it should look reasonable in the way it appears when rendered (a) on the docsite, and (b) via Github. Do both look OK to you?

**Comment by liammulh** [comment]
It seems a bit strange on GitHub as well. But I understand that we're running up against the limitations of Mkdocs. As long as the docsite looks reasonable and the important docs look good on GitHub, I think it's fine.

**Comment by liammulh** [comment]
We discussed this PR in last week's meeting, and from what I recall, we're all OK with the tradeoffs involved in this approach. Merging.

**Pull request merged**
