### PR TITLE
Gallery integration

### PR DESCRIPTION
**Pull request by kaldis-berzins**
By submitting this PR, I am indicating to the Numberscope maintainers that I have read and understood the [contributing guidelines](https://numberscope.colorado.edu/doc/CONTRIBUTING/) and that this PR follows those guidelines to the best of my knowledge. I have also read the [pull request checklist](https://numberscope.colorado.edu/doc/doc/pull-request-checklist/) and followed the instructions therein.

<hr/>
This PR is number 5 in the PR merge chain.

# Gallery Integration
## Thumbnails
 - Added thumbnails to gallery cards. They are essentially just specimens contained entirely within a little 200x200 container.
 - Thumbnails own their specimen, so the cards must retrieve the name of the specimen on their own.
    - Two methods were added to `Specimen.ts` to enable this: `getNameFromURL` and `getSequenceNameFromURL`.
 - Thumbnails are virtually unchanged in later PRs.
 ## Gallery
 - Has two sections: Saved specimens and Featured specimens.
 - We didn't have time to fully implement the design that we had envisioned, we hope that making a (hopefully) coherent PR chain was more valuable to you.
 - Saving specimens should work at this point and loading them from the gallery should be possible.
 - Featured specimens can be easily added to the list by editing `shared/defineFeatured.ts`. This file will automatically turn into cards on the gallery page.
 - Significant changes to the gallery don't come in later PRs.
## Scope
 - Current specimen is now saved in browser as well

### CODE REVIEW

**Comment by gwhitney** [comment]
Beginning cleaning of this PR

**Comment by gwhitney** [comment]
@kaldis-berzins or @maxd0328 or colleagues: This PR removes tests from browserCaching.spec.ts but does not replace them with updated versions reflecting the api changes to browserCaching.ts. If any of you are able to supply updated tests, they will be needed for (the cleaned version) of this PR to be merged. Thanks.

**Comment by gwhitney** [comment]
@kaldis-berzins or @maxd0328 or colleagues: You say above that you "didn't have time to fully implement the design that [you] had envisioned," and we totally respect that, and do appreciate your delivering a reasonably coherent PR chain, but it would be very helpful if you could post some summary of the envisioned design and the implemented design and how they differ so that we can judge how best to proceed here. Thank you so much.

**Comment by kaldis-berzins** [comment]
@gwhitney the envisioned design looked like this:
Desktop - 5

The saved specimens would have their own tab here and the vertical categories were used for different visualizers.
In the version we delivered we used the vertical categories to separate saved from featured visualizers.

**Comment by gwhitney** [comment]
> @gwhitney the envisioned design looked like this:

Thanks, that's very helpful!

**Comment by gwhitney** [comment]
Closing in favor of #368.

**Pull request closed without merging**
