### PR TITLE
[WIP] Set Up Jest

### PR DESCRIPTION
**Pull request by liam-mulhall**
In this PR, we install Jest, configure it for TypeScript, and add docs for unit tests and integration tests.

### CODE REVIEW

**Comment by gwhitney** [comment]
OK, that's something. Thanks! I'll see if we can get #29 resolved, and if that's not going to happen quickly, I will review with just the trivial test (which I gather works OK).

**Comment by liam-mulhall** [comment]
OK, I've added a basic unit test suite for `VisualizerDefault` that should pass if you run `jest`. Sorry this took so long. I ended up having some personal issues last Friday that prevented me from working on this.

**Comment by gwhitney** [comment]
Please message me again if it's helpful to your work flow for me to review this tonight; otherwise, I will likely do it tomorrow, sometime after the meeting.

**Comment by gwhitney** [comment]
@liam-mulhall I have `npm run serve` producing a working UI in branch main, but producing an empty browser screen with no interaction with this PR. Please confirm you replicate this difficulty and correct if so. Thanks.

**Comment by gwhitney** [comment]
Liam has in fact confirmed the regression in this PR, and found it quite possibly related to webpack misbundling of Jest with with the frontscope Vue app, but is still working on resolution. Obviously I will work to get this merged as rapidly as possible when the difficulty is resolved, as testing in place puts all future PRs on firmer footing (and I am also happy to help debug if you feel you're going in circles at any point, Liam).

**Comment by gwhitney** [comment]
(The "please revise" label can be removed when this PR is again ready for review.)

**Comment by gwhitney** [comment]
Note that @liam-mulhall indicated in #72 that the intention is to abandon this PR when all of its content has reached main by way of other PRs. Hence, I will mark this as [WIP] and remove the please revise tag.

**Comment by liam-mulhall** [comment]
I'm going to close this because the upgrade to Vue 3 will obviate the need for this PR. (The upgrade to Vue 3 will include a testing framework that can test TS files.)

**Pull request closed without merging**
