### PR TITLE
doc: Update contributors and current leadership of project

### PR DESCRIPTION
**Pull request by gwhitney**
By submitting this PR, I am indicating to the Numberscope maintainers that I have read and understood the [contributing guidelines](https://numberscope.colorado.edu/doc/CONTRIBUTING/) and that this PR follows those guidelines to the best of my knowledge. I have also read the [pull request checklist](https://numberscope.colorado.edu/doc/doc/pull-request-checklist/) and followed the instructions therein.

<hr/>

Just trying to get the about page up-to-date with new folks coming in.

### CODE REVIEW

**Review by katestange — CHANGES_REQUESTED** [review]
Please make it Katherine E. Stange (more official?) and add Clyde Kertzer?

**Comment by gwhitney** [comment]
OK, as you are mentioned twice, I left the first one as Dr. Katherine E. Stange, and changed the second to just Katherine Stange. Does that seem OK? Also, I looked and as far as I can see, no code from Clyde is actually merged yet. So the time to add him would be when something is merged (and there is actually an item in the PR checklist for doing that, if we were just taking the time to go through the checklist every time instead of being in such a blazing rush).

**Comment by katestange** [comment]
> I looked and as far as I can see, no code from Clyde is actually merged yet. So the time to add him would be when something is merged (and there is actually an item in the PR checklist for doing that, if we were just taking the time to go through the checklist every time instead of being in such a blazing rush).

The list partially pre-dates the move to github and includes all the students that worked on the project in any capacity, even if they don't have code in the current version right now.  Unless we want to sort that all out retroactively and (re)move some names, I think it's fair to include Clyde, because he is in the same boat at the moment.  These other students who haven't checked in code have contributed in various ways including brainstorming, forming ideas, using numberscope, participating in discussions, creating prototypes etc. etc.  So I want to honour that.  If "contributors" means actual code, then we may need two lists, "code contributors" and "numberscope project contributors" or something.

**Comment by gwhitney** [comment]
All good. Definitely no reason to be stingy with credit. I just didn't realize the membership of this list.

**Review by katestange — APPROVED** [review]
Looks good now!

**Pull request merged**
